package avfont.com.aviator.aviatorfontlib;

import android.content.Context;

/**
 * Created by Aviator on 4/22/2018.[Tranquilizer]
 */

 interface  FontNames {
    String[]  FontsNames(Context context);
    String[]  AllFontNames={
            "Alarabiya.ttf",
            "AlMajd.ttf",
            "Almohannad.ttf",
            "Android Insomnia Regular.ttf",
            "AndroidClock.ttf",
            "Bauhaus.ttf",
            "BowBabyFlo.ttf",
            "CarroisGothicSC-Regular.ttf",
            "CaviarDreams.ttf",
            "Cheri.ttf",
            "Comfortaa.ttf",
            "CutiveMono.ttf",
            "DancingScript-Bold.ttf",
            "DroidSans.ttf",
            "DroidSans-Bold.ttf",
            "DroidSansFallback.ttf",
            "DroidSansMono.ttf",
            "eightyshades.ttf",
            "FreeSansBold.ttf",
            "HappyGiraffe.ttf",
            "Iphone.ttf",
            "Mobily.ttf",
            "Motla_bold.ttf",
            "Nekar.ttf",
            "NotoSansAvestan-Regular.ttf",
            "NotoSansBamum-Regular.ttf",
            "NotoSansBatak-Regular.ttf",
            "NotoSansBrahmi-Regular.ttf",
            "NotoSansCarian-Regular.ttf",
            "NotoSansCham-Bold.ttf",
            "NotoSansCham-Regular.ttf",
            "NotoSansCherokee-Regular.ttf",
            "NotoSansCoptic-Regular.ttf",
            "NotoSansCuneiform-Regular.ttf",
            "NotoSansCypriot-Regular.ttf",
            "NotoSansEgyptianHieroglyphs-Regular.ttf",
            "NotoSansImperialAramaic-Regular.ttf",
            "NotoSansInscriptionalPahlavi-Regular.ttf",
            "NotoSansInscriptionalParthian-Regular.ttf",
            "NotoSansJavanese-Regular.ttf",
            "NotoSansKaithi-Regular.ttf",
            "NotoSansKayahLi-Regular.ttf",
            "NotoSansLepcha-Regular.ttf",
            "NotoSansLinearB-Regular.ttf",
            "NotoSansLisu-Regular.ttf",
            "NotoSansLycian-Regular.ttf",
            "NotoSansLydian-Regular.ttf",
            "NotoSansMandaic-Regular.ttf",
            "NotoSansMeeteiMayek-Regular.ttf",
            "NotoSansOlChiki-Regular.ttf",
            "NotoSansOldSouthArabian-Regular.ttf",
            "NotoSansRejang-Regular.ttf",
            "NotoSansSamaritan-Regular.ttf",
            "NotoSansSaurashtra-Regular.ttf",
            "NotoSansSundanese-Regular.ttf",
            "NotoSansSymbols-Regular-Subsetted.ttf",
            "NotoSansSyriacEastern-Regular.ttf",
            "NotoSansSyriacEstrangela-Regular.ttf",
            "NotoSansSyriacWestern-Regular.ttf",
            "NotoSansTaiTham-Regular.ttf",
            "NotoSansTaiViet-Regular.ttf",
            "NotoSansVai-Regular.ttf",
            "NotoSerif-Bold.ttf",
            "NotoSerif-BoldItalic.ttf",
            "NotoSerif-Italic.ttf",
            "NotoSerif-Regular.ttf",
            "nucleo-outline.ttf",
            "orange_juice.ttf",
            "Passing_Notes.ttf",
            "ProductSans.ttf",
            "Rekaa.ttf",
            "Roboto-Black.ttf",
            "Roboto-BlackItalic.ttf",
            "Roboto-Bold.ttf",
            "Roboto-BoldItalic.ttf",
            "RobotoCondensed-Bold.ttf",
            "RobotoCondensed-BoldItalic.ttf",
            "RobotoCondensed-Italic.ttf",
            "RobotoCondensed-Light.ttf",
            "RobotoCondensed-LightItalic.ttf",
            "RobotoCondensed-Regular.ttf",
            "Roboto-Italic.ttf",
            "Roboto-Light.ttf",
            "Roboto-LightItalic.ttf",
            "Roboto-Medium.ttf",
            "Roboto-MediumItalic.ttf",
            "Roboto-Regular.ttf",
            "Roboto-Thin.ttf",
            "Roboto-ThinItalic.ttf",
            "solid_3d.ttf",
            "Transformers.ttf",
            "woodcutter_carnage.ttf",
            "youngones_RS-Regular.ttf",
            "Zaman.ttf"
    };
}
